// <auto-generated />
using System;
using CalculadoraCostes.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraCostes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CalculadoraDbContext))]
    [Migration("20251106075518_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculadoraCostes.Domain.Entities.Energy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseEnergyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ConsumptionPer100Km")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EmissionFactorPerUnit")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("EmissionReduction")
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid?>("EmissionReferenceEnergyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Family")
                        .HasColumnType("int");

                    b.Property<bool>("InheritEmissionFromBase")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("PricePerUnit")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("RenewableShare")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("RentingCostPerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaseEnergyId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EmissionReferenceEnergyId");

                    b.ToTable("Energies", (string)null);
                });

            modelBuilder.Entity("CalculadoraCostes.Domain.Entities.EnergyCostComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EnergyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ValueType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnergyId", "Key")
                        .IsUnique();

                    b.ToTable("EnergyCostComponents", (string)null);
                });

            modelBuilder.Entity("CalculadoraCostes.Domain.Entities.SystemParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEditable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemParameters", (string)null);
                });

            modelBuilder.Entity("CalculadoraCostes.Domain.Entities.Energy", b =>
                {
                    b.HasOne("CalculadoraCostes.Domain.Entities.Energy", null)
                        .WithMany()
                        .HasForeignKey("BaseEnergyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CalculadoraCostes.Domain.Entities.Energy", null)
                        .WithMany()
                        .HasForeignKey("EmissionReferenceEnergyId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CalculadoraCostes.Domain.Entities.EnergyCostComponent", b =>
                {
                    b.HasOne("CalculadoraCostes.Domain.Entities.Energy", "Energy")
                        .WithMany("CostComponents")
                        .HasForeignKey("EnergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Energy");
                });

            modelBuilder.Entity("CalculadoraCostes.Domain.Entities.Energy", b =>
                {
                    b.Navigation("CostComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
